table dim_tiempo
	lineageTag: 74cece3f-df53-4564-9a26-7352b177a9e4

	column id_periodo
		dataType: int64
		formatString: 0
		lineageTag: a1aeae3d-43ba-4fe9-81bf-ec2aacd88ac6
		summarizeBy: none
		sourceColumn: id_periodo

		annotation SummarizationSetBy = Automatic

	column anio_titulo
		dataType: int64
		formatString: 0
		lineageTag: 17973d73-eab0-4e85-b3fb-fd8b29be5137
		summarizeBy: none
		sourceColumn: anio_titulo

		annotation SummarizationSetBy = Automatic

	column semestre_titulo
		dataType: int64
		formatString: 0
		lineageTag: 7fd62935-119f-45db-8c43-e341fe84bead
		summarizeBy: none
		sourceColumn: semestre_titulo

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: string
		lineageTag: 44ffe545-2549-4beb-8a3a-7b8859b7fbbc
		summarizeBy: none
		sourceColumn: periodo
		sortByColumn: id_periodo

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition dim_tiempo = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\IA Development\proyecto-titulados\powerbi\dim_tiempo.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id_periodo", Int64.Type}, {"anio_titulo", Int64.Type}, {"semestre_titulo", Int64.Type}, {"periodo", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

