table dim_institucion
	lineageTag: 7ced6fb5-a508-415f-a721-f5f53ae1f304

	column cod_inst
		dataType: int64
		formatString: 0
		lineageTag: 3e7dad21-6c07-430a-a1c1-a616f3e35ebb
		summarizeBy: none
		sourceColumn: cod_inst

		annotation SummarizationSetBy = Automatic

	column nomb_inst
		dataType: string
		lineageTag: c7c54b27-4d0f-46dd-90d6-7f6e1f3b5dbe
		summarizeBy: none
		sourceColumn: nomb_inst

		annotation SummarizationSetBy = Automatic

	column tipo_inst_1
		dataType: string
		lineageTag: 3400738b-9742-405e-afd3-cdbfe3f9a5d6
		summarizeBy: none
		sourceColumn: tipo_inst_1

		annotation SummarizationSetBy = Automatic

	column tipo_inst_2
		dataType: string
		lineageTag: 2ab65c6c-e06b-4252-a7b2-959f7c2ce740
		summarizeBy: none
		sourceColumn: tipo_inst_2

		annotation SummarizationSetBy = Automatic

	partition dim_institucion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\IA Development\proyecto-titulados\powerbi\dim_institucion.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cod_inst", Int64.Type}, {"nomb_inst", type text}, {"tipo_inst_1", type text}, {"tipo_inst_2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

